steps: 
- name: 'gcr.io/cloud-builders/go'
  args: ['install', 'hello']
  env: ['GOPATH=./']

- id:  'Rodando teste unitário'  
  name: 'gcr.io/cloud-builders/go'
  args: ['test', 'hello']
  env: ['GOPATH=./']

- id: "Gerando Build"
  name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/app-go:$SHORT_SHA', '-f','Dockerfile','.']

- id: "pushing image"
  name: 'gcr.io/cloud-builders/docker'
  args: ['push','gcr.io/$PROJECT_ID/app-go:$SHORT_SHA' ]   

- id: "Adjusting deployment file - k8"
  name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: '/bin/sh'
  args:
    - '-c'
    - |
      sed 's#img-app-deployment#gcr.io/$PROJECT_ID/app-go:$SHORT_SHA#g' k8/deployment.yaml > k8/deployment-new.yaml;
      cat k8/deployment-new.yaml    

- id: "Deployment k8"
  name: 'gcr.io/cloud-builders/kubectl'
  args:
    - 'apply'
    - '-f'
    - 'k8/deployment-new.yaml'      
  env: 
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=cluster-docker-go'  