apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: go-hpa
spec:
 replicas: 1
 template:
    metadata:
      labels:
        app: app-go
    spec:
      containers:
      - name: go-hpa
        image: img-app-deployment
        ports:
        - containerPort: 80  
  